name: should-publish-module-kbupdate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: pwsh

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.NEWPAT}}

    steps:
      - uses: actions/checkout@v2
      - name: 🧐 Check to see if the module has been updated since latest zip
        id: zipcheck
        run: |
          $parms = @{
            Uri                  = "https://catalog.s.download.windowsupdate.com/microsoftupdate/v6/wsusscan/wsusscn2.cab"
            Method               = "HEAD"
            SkipHeaderValidation = $true
            ErrorAction          = "Stop"
          }
          $request = Invoke-WebRequest @parms
          $catalogdate = [datetime]($request.Headers['Last-Modified'] | Select-Object -First 1)
          $publishdate = (Find-Module kbupdate-library).PublishedDate

          Write-Warning "Module pub date: $publishdate"
          Write-Warning "Catalog pub date: $catalogdate"

          if ($publishdate -le $catalogdate) { #le for final
            Write-Output '::set-output name=newpub::true'
          } else {
            Write-Output '::set-output name=newpub::false'
          }

      - name: 👥 Run workflow
        if: steps.zipcheck.outputs.newpub == 'true'
        run: |
          gh workflow run kbupdate.yml
          Write-Output "Visit https://github.com/potatoqualitee/releases/actions/workflows/kbupdate.yml"

      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: keepalive to prevent workflow deactivation
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
